
helloworld:
	vasm src/AST_HelloWorld.asm -chklabels -nocase -Dvasm=1 -L listings/AST_HelloWorld.asm -DBuildAST=1 -Felf -o build/AST_HelloWorld.elf
	vlink build/AST_HelloWorld.elf -o ~/emu/Atari\ ST/atarist-hd-2/HLLWRLD.TOS -bataritos 

