linea:
	m68k-atari-mint-gcc ./lineablit.c -o LNABLT.TOS -std=c99 -O3
omni:
	m68k-atari-mint-gcc ./omniscroll.c -o OMNISCRL.TOS -std=c99 -O3
#	m68k-atari-mint-gcc ./horiz-lo.c -o HRZLO.TOS -std=c99 -O3
#	m68k-atari-mint-gcc ./mazescroll-hi.c -o MZSCRLHI.TOS -std=c99 -O3