tos:
	m68k-atari-mint-gcc ./bench.c -o BENCH0.TOS  -std=c99 -O0
	m68k-atari-mint-gcc ./bench.c -o BENCH1.TOS  -std=c99 -O1
	m68k-atari-mint-gcc ./bench.c -o BENCH2.TOS  -std=c99 -O2
	m68k-atari-mint-gcc ./bench.c -o BENCH3.TOS  -std=c99 -O3
	